services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    restart: "always"
    ports:
      - "27017:27017"
  data-generator:
    build: "data-generator/"
    depends_on:
      - mongodb
    restart: "always"
  backend:
    build: "backend/"
    depends_on:
      - mongodb
    restart: "always"

    ports:
      - "8080:8080"
  
